name: Build

on:
    push:
        tags:
            - "*"

jobs:
    build-kindle:
        name: Build Kindle
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
            actions: write
            attestations: write
            id-token: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
              with:
                  persist-credentials: false

            - name: Install dependencies
              run: |
                  sudo apt update
                  sudo apt install -y just zip

            - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29

            - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659
              with:
                  cache-key: "kindle"
                  target: armv7-unknown-linux-musleabihf
                  rustflags: ""

            - name: Install cargo-zigbuild
              run: cargo install --locked cargo-zigbuild

            - name: Build
              run: just build

            - name: Make KUAL extension
              run: |
                  mv target/armv7-unknown-linux-musleabihf/release/kinshare-client extension/bin/kinshare-client
                  mv extension kinshare
                  zip -r kinshare.zip kinshare

            - name: Upload
              uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228
              with:
                  files: kinshare.zip
    build-desktop:
        name: Build Desktop (${{ matrix.target }})
        runs-on: ${{ matrix.os }}
        permissions:
            contents: write
            packages: write
            actions: write
            attestations: write
            id-token: write
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu
                      output: kinshare-desktop

                    - os: windows-latest
                      target: x86_64-pc-windows-msvc
                      output: kinshare-desktop.exe

                    - os: macos-latest
                      target: aarch64-apple-darwin
                      output: kinshare-desktop
        steps:
            - name: Checkout repository
              uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
              with:
                  persist-credentials: false

            - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659
              with:
                  cache-key: ${{ matrix.target }}
                  target: ${{ matrix.target }}
                  rustflags: ""

            - name: Build
              run: cargo build --release --bin kinshare-desktop --target ${{ matrix.target }}

            - name: Rename
              run: |
                  mv target/${{ matrix.target }}/release/${{ matrix.output }} ${{ matrix.target }}-${{ matrix.output }}

            - name: Upload
              uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228
              with:
                  files: ${{ matrix.target }}-${{ matrix.output }}
