name: Build

on:
    push:
        tags:
            - "*"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            actions: write
            attestations: write
            id-token: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
              with:
                  persist-credentials: false

            - name: Install just
              run: |
                  sudo apt update
                  sudo apt install -y just

            - name: Install zig
              run: |
                  case ${{ runner.arch }} in
                    X86) ARCH="x86" ;;
                    X64) ARCH="x86_64" ;;
                    ARM) ARCH="arm" ;;
                    ARM64) ARCH="aarch64" ;;
                  esac

                  curl -O "https://ziglang.org/download/0.16.0/zig-${ARCH}-linux-0.16.0.tar.xz"
                  tar xf "zig-${ARCH}-linux-0.16.0.tar.xz"
                  echo "zig-${ARCH}-linux-0.16.0" >> $GITHUB_PATH

            - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659
              with:
                  target: armv7-unknown-linux-musleabihf

            - name: Install cargo-zigbuild
              run: cargo install --locked cargo-zigbuild

            - name: Build
              run: just build

            - name: Upload
              uses: softprops/action-gh-release@v2
              with:
                  files: target/armv7-unknown-linux-musleabihf/release/kinshare-client
