[package]
name = "desktop"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
server = { path = "../server" }
anyhow = { workspace = true }
tokio = { workspace = true }
bytemuck = { version = "1", features = ["derive"] }
iced = { version = "0.14", features = ["tokio"] }
